// import Factory from '@ioc:Adonis/Lucid/Factory';
import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Employee from 'App/Models/Employee';

export default class extends BaseSeeder {
  public async run () {
   await Employee.createMany([
      {
        
          firstName: 'Humphrey',
          lastName: 'Singculan',
          birthdate: '06-23-1999',
          gender: 'Male',
          maritalStatus: 'Double',
          department: 'IT Department',
          position: 'Temporary Worker',
          dateHired: '09-27-2022',
          employmentStatus: 'Employed',
          contactNumber: '09397535416',
          email: 'Humfurie@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Employed',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Lendon',
          lastName: 'Espinosa',
          birthdate: '01-09-1998',
          gender: 'Male',
          maritalStatus: 'Married',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'lendon@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Schema',
          lastName: 'Logy',
          birthdate: '11-11-2018',
          gender: 'Male',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        },
        {
          firstName: 'Gwyneth',
          lastName: 'Singculan',
          birthdate: '05-04-2004',
          gender: 'Female',
          maritalStatus: 'Single',
          department: 'Arts',
          position: 'Part-Timer',
          dateHired: '09-27-2022',
          employmentStatus: 'Hired',
          contactNumber: '09397535416',
          email: 'gwyneth@gmail.com',
          address:  'Poblacion Cordova Cebu',
          city:  'Cebu City',
          province:  'Cebu',
          nationality: 'Filipino',
        }
  
    ])
    //  Factory.model('App/Models/Employee').createMany(30);

  }
}
